### PR TITLE
Add smart battery communication

### PR DESCRIPTION
**Pull request by AlexKlimaj**

### CODE REVIEW

**Comment by WickedShell** [comment]
You have not proposed any specific new fields, or additions to the message.

**Comment by AlexKlimaj** [comment]
Ah sorry, I left them out. 

https://github.com/mavlink/mavlink/pull/907

**Comment by AlexKlimaj** [comment]
Any comments or feedback?

**Comment by hamishwillee** [comment]
The smart battery messages were iterated outside this RFC and have been submitted as WIP in https://github.com/mavlink/mavlink/pull/1072

@LorenzMeier What happens when changes associated with an RFC get merged into codeline? Should the original RFC be accepted, or does it get updated with link to final information, or does it get closed. 
FYI, I have no rights in this repo, so whatever option is taken, will have to be taken by someone else!

**Comment by AlexKlimaj** [comment]
@hamishwillee I have the ability to close the PR since I opened it.

**Comment by hamishwillee** [comment]
Thanks @AlexKlimaj . Before doing that, I'd like to understand the process.

What I'd "think" it would be is that the PR would be updated with a summary of the actual end implementation, links to the new messages and any implementation, and then merged. This would then be a permanent record of the discussion and change. However that would require someone does the work. 

Closing an RFC PR would indicate that the change was rejected.

**Comment by khedkarmohan1995** [comment]
Hello sir,i am trying to write code for getting data(Voltage,current and temperature) from gauge(bq40z50R2) in micro-controller (stm32l476RC) using STM32CubeMX tool.But unable to write code.Please,give me suggestion.

Thanks
Mohan

**Comment by hamishwillee** [comment]
@khedkarmohan1995 Please don't add support questions to RFCs. Look at the support channels: https://mavlink.io/en/about/support.html

**Comment by hamishwillee** [comment]
@AlexKlimaj Please close this RFC. I've decided that is OK because we didn't implement the changes as suggested.

FYI Anyone interested, the smart battery service was implemented as shown.

- Messages:
  - [SMART_BATTERY_INFO](https://mavlink.io/en/messages/common.html#SMART_BATTERY_INFO)
  - [SMART_BATTERY_STATUS](https://mavlink.io/en/messages/common.html#SMART_BATTERY_STATUS)
- Enum:
  - [MAV_SMART_BATTERY_FAULT](https://mavlink.io/en/messages/common.html#MAV_SMART_BATTERY_FAULT)

**Comment by hamishwillee** [comment]
@AlexKlimaj Further to above, did you implement the smart battery messages and test this in anger? If so, on what stacks/GCS? 
Did they what is needed? Is there any improvement we should make.
I'd like to remove the WIP on these messages if they are tested and we are happy.

**Comment by AlexKlimaj** [comment]
I have not had a chance to test the mavlink message as implemented. I am working on a smart battery that will use UAVCAN. I will be able to test the mavlink message once that is up and running. 

Overall, while this process took long to complete, it spawned a great discussion around the smart battery message and I feel it was implemented well. 

[For reference the discussion was here. ](https://github.com/mavlink/mavlink/issues/988)
[And the message was implemented here.](https://github.com/mavlink/mavlink/pull/1072)

**Pull request closed without merging**
