### PR TITLE
RFC 0011: MAVLink SDK

### PR DESCRIPTION
**Pull request by JonasVautherin**

### CODE REVIEW

**Comment by bys1123** [comment]
Did you considered call it “MAVSDK”?
1. Easier to remember, type, and pronounce. 
2. Easier to make a logo. 
3. Inherit the naming strategy of "mavros", and make it have differentiation with "mavros", easier to understand what that is. 
4. Avoid a hyphen in package and repo name. 
5. MAVLink SDK looks like an SDK for developing MAVLink. 
6. "mav" is enough to presents "MAVLink" as it's already a standard.

All from marketer opinion. The final decision is in your court.

**Comment by magicrub** [comment]
I'm happy with a rebrand since "MAV" is not really the term that caught on like "drone" and "UAV" did. When new people who aren't in the drone circles see mav they don't relate it to miro air vehicle. Mav is just the name of something. It's all about "drone" this and that. Sooo, it seems like "mav" in MAVLink has sort of a become a brand in itself.

**Comment by mrpollo** [comment]
The way I see it, there are two proposals here, moving the project under mavlink governance, and renaming the project. I have a few comments on both.

## Move the SDK to the MAVLink org
I think it should be clear what are the implications and intent behind this for maintainers, future contributors, and the broader open source community, if we don't clarify this, we might end up causing even more considerable confusion.

- is anything changing from a developer perspective?
- is the maintainer group the same?
- what is the role of the current MAVLink maintenance group on the SDK if this move happens?
- what is the role of the SDK on the mavlink org, is the intention to make it the "official" SDK?

## Rename the SDK to "MAVLink SDK"
I think the proposed naming makes a lot of sense, and we should do a better job at naming the tools we depend on, we have historically been terrible at this.

- My biggest problem with the current name "Dronecode SDK" is developers calling it plain "Dronecode," I fear "MAVLink SDK" will have the same side effect which will cause a troubleshooting nightmare.
- I agree with @magicrub, "MAV" sticks better

**Comment by hamishwillee** [comment]
On the name ...

@JonasVautherin Interesting that we had that whole discussion about good names and no one came up with MAVSDK until @bys1123 :-) 

I prefer it for all the reasons above. 
In addition, I always felt that "MAVLink SDK" as a name somewhat implied that the SDK was the "only mavlink SDK", "recommended mavlink SDK" and "official mavlink SDK". The new name allows us to define that positioning separately, which is a good thing. 

Unless there are strong objections or a better suggestion in the MAVLink dev meeting this week, I think we should make this update.

**Comment by hamishwillee** [comment]
IMO the RFC should also be updated to answer Ramon's questions about what it means to move to the org. FWIW, my thoughts:

> is anything changing from a developer perspective?

Not really. 

The main change is one of perception - we hope this developers will see this as a true generic MAVLink API rather than something that works only with PX4.

Note that the SDK core and generic plugins are (and have always been) intended to match the MAVLink specification. We encourage contributors to match the MAVLink specification in their flight stacks in order to work with the SDK "out of the box". 

We will also take dialects and core spec variations as plugins with some caveats:
- this should have adequate automated testing to the same quality level as standard plugins. "Someone" may need to do some work to allow integration for testing against different flight stacks.
- the contributor must commit to maintain the code
- If it not maintained it might be removed (i.e. to an out of tree branch)

AFAIK none of this is different to how MAVLink treats code contributions.

> is the maintainer group the same?
> what is the role of the current MAVLink maintenance group on the SDK if this move happens?

These are questions to be resolved, but IMO 
- the total people with maintenance _rights_ should expand to be the superset of the current MAVLink and SDK teams (ie both teams get full rights over both areas).
- The actual people doing the work in each area is likely to remain the same.
- Note also there is a somewhat schizophrenic ownership split half way down the project because the generator code is in ArduPilot/pymavlink, and that has a different set of owners. FWIW to be inclusive all those people should be invited to be members of the MAVLink/SDK org even if the invite is not reciprocated.

> what is the role of the SDK on the mavlink org, is the intention to make it the "official" SDK?"

I would say the aim is to make it **an** official SDK, in that it is supported and maintained within the MAVLink org but without the implication that it is the only or necessarily best stack for every flight stack. 

The reason being that it will provide a cross platform implementation of the GCS (non-autopilot) side of the most common microservices, *according to the MAVLink specification*. 
In order to keep it realistically useful though, it will allow flight stacks to provide implementation of their own dialects and behaviours through their own plugins.

**Comment by auturgy** [comment]
The discussion above makes sense to me, although I might be an outlier in that I prefer “MavLink SDK” as the name. That said, I think a rename would cause more confusion than clarification until the SDK actually is agnostic.
As for relocating to the Mavlink org: again makes sense if the intent is for it to be flight stack agnostic - but as I’m not a maintainer of either Mavlink or the sdk, I don’t think I should really be part of that decision.

**Comment by JonasVautherin** [comment]
Thanks for the comments, I will update the RFC to reflect the current state of the discussion.

It seems like most people (sorry @auturgy :smile:) like `mavsdk` more than `MAVLink SDK`. I do agree with the points mentioned above regarding that. I like the consistency in the `MAV-` naming scheme (`MAVLink`, `MAVROS`, `MAVSDK`) and the fact that it cannot be shortened. We have seen the `DronecodeSDK` being called `Dronecode` quite a lot, and that is a problem. I don't see how `MAVSDK` could become an issue in that regard :-).

I have a few questions regarding maintainers and contributions:

> the total people with maintenance rights should expand to be the superset of the current MAVLink and SDK teams (ie both teams get full rights over both areas).

@hamishwillee: I am not sure what the implications of that is. Is that how it works for, say, QGC? Does that mean that somebody from the MAVLink team could theoretically merge PRs without the "active maintainers" (e.g. currently @julianoes or @JonasVautherin) approval?

> As for relocating to the Mavlink org: again makes sense if the intent is for it to be flight stack agnostic

IMO the intent is to make it flight stack agnostic. Now one question is this: is that enough for a new PR to implement "MAVLink-common" AND to not break other flight stacks, or does "flight stack agnostic" mean that a PR must test all the flight stacks to be accepted and merged?

I would say that a PR should honor "MAVLink-common", but then it is perfectly fine to add support for one stack only (given that it doesn't break the tests). This means that we may end up with features tested only in one flight stack, but it makes it more realistic for contributors. In that sense, I don't see a problem with renaming and moving the DronecodeSDK right now. It may not support all stacks yet, but future contributions will improve that, and it won't break anybody's flow.

**Comment by hamishwillee** [comment]
> Does that mean that somebody from the MAVLink team could theoretically merge PRs without the "active maintainers" (e.g. currently @julianoes or @JonasVautherin) approval?

That was my argument. Happy for you to disagree - it doesn't matter: the point is that we need to decide what the rules are and put them in the doc. What we want to avoid, if possible, is bottlenecks on a small number of people, and cases where we irritate our community by not having clear rules. 

> IMO the intent is to make it flight stack agnostic.

Yes. It definitely does not mean "must run against all flight stacks to be accepted" because a particular flight stack might not be compliant or not implement particular services even within common. On top of that we want to be able to support integration with dialects. 

So tests need to be _able to_ run against any flight stack and provide meaningful reports on success or fail. I'd think we should by default run common against any flight stack that wants to provide an integration with our test interfaces (which need to be flexible enough to allow integration).  Probably we need to differentiate between core and dialect plugins in tests so some are just run against particular flight stacks.

As an aside, I'm hoping that in parallel with development of the implementation the docs can be updated so that we have both a description of the protocol, a test of the non-autopilot side in the SDK, and a test of the autopilot side in whatever platform does the implementation.

**Comment by hamishwillee** [comment]
@mrpollo Do you feel that @JonasVautherin Changes to the RFC have addressed your main points in https://github.com/mavlink/rfcs/pull/15#issuecomment-491408407 ?

**Comment by mrpollo** [comment]
Ownership is clear, maintainers have a shared goal and the mavlink org is benefiting from contributions. The RFC even touches on not being _the only_ option, being inclusive of other tools like `Pymavlink` and `DroneKit-flavors`. 👍

**Pull request merged**
