### PR TITLE
RFC 0011 - Companion Status message

### PR DESCRIPTION
**Pull request by baumanta**
RFC for a companion status message

### CODE REVIEW

**Comment by thomasgubler** [comment]
Summary from discussion on slack:
We should discuss if this could be integrated into the heartbeat message.

FYI @bkueng @TSC21 @LorenzMeier

**Comment by thomasgubler** [comment]
There was some discussion in the px4 dev call and offline which I try to summarize here to keep everyone in the loop.

* The general naming was an issue: companion_* should be companion_process_* (companion_status to companion_process_status) to make more clear that this is about processes an not the whole companion computer
* Regardless of the naming issues the px4 dev team reconsidered the need for this status message. We currently think similar functionality is achievable via a heartbeat message (for crude state according to MAV_STATE) and a rtps (unrelated to mavlink, see https://dev.px4.io/en/middleware/micrortps.html)  message for more detailed state. Probably this will require an addition to the MAV_TYPE enum.

@baumanta is currently investigating the details. For now this RFC is on hold.

**Comment by thomasgubler** [comment]
Actually the correct way to identify the companion process is by component id and not by mav_type I think

**Comment by LorenzMeier** [comment]
Closing as stale.

**Pull request closed without merging**
